name: Publish
on:
  push:
    branches:
      - credentials

jobs:

  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@credentials

    - name: Commit and push updated version
      run: git commit -m "empty commit" --allow-empty & git push
