name: Publish
on:
  push:
    branches:
      - credentials

jobs:

  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: git config email
      run: git config user.email "cicd@bot.com"

    - name: git config name
      run: git config user.name "CICD BOT"

    - name: Commit and push updated version
      run: git commit -m "empty commit" --allow-empty --author="CICD BOT <cicd@bot.com>"

    - name: push
      run: git push
